// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID               string
	TaskID           string
	StageID          string
	Kind             string
	RetryNo          int
	Status           string
	Title            string
	Content          string
	DecisionFeedback *string
	EditedContent    *string
	DecidedBy        *string
	DecidedVia       *string
	ResumePending    bool
	RequestedAt      pgtype.Timestamptz
	DecidedAt        pgtype.Timestamptz
	Version          int
}

type Deliverable struct {
	ID        string
	TaskID    string
	StageID   string
	Kind      string
	Uri       *string
	Content   *string
	CommitSha *string
	Summary   *string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID             string
	Name           string
	GithubOwner    string
	GithubRepo     string
	DefaultBranch  string
	InstallationID pgtype.Int8
	ContextPath    string
	LocalPath      *string
	TokenBudget    int64
	CreatedAt      pgtype.Timestamptz
}

type Stage struct {
	ID                 string
	TaskID             string
	StageKey           string
	Role               string
	DependsOn          []string
	Status             string
	RetryCount         int
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	Plan               *string
	PlanRetryNo        int
	DeliverableRef     *string
	DeliverableSummary *string
	DeliverableRetryNo int
	LastFeedback       *string
	BlockedReason      *string
	Attempt            int
	LeaseOwner         *string
	LeaseUntil         pgtype.Timestamptz
	Version            int
}

type Task struct {
	ID              string
	ProjectID       string
	Command         string
	Status          string
	DiscordThreadID *string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int
	Pipeline        []byte
	Workspace       *string
	EventSeq        int64
}

type TaskEvent struct {
	ID       int64
	EventID  string
	TaskID   string
	Seq      int64
	StageKey *string
	Agent    *string
	Type     string
	Payload  []byte
	Ts       pgtype.Timestamptz
}

type UsageRecord struct {
	ID               int64
	TaskID           string
	StageKey         *string
	Agent            *string
	Model            string
	InputTokens      int64
	OutputTokens     int64
	Ts               pgtype.Timestamptz
	CacheReadTokens  int64
	CacheWriteTokens int64
}
