// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimStage = `-- name: ClaimStage :one
update stage set status=$3,attempt=attempt+1,version=version+1,started_at=coalesce(started_at,now()) where id=$1 and attempt=$2 and status=$4 returning attempt
`

type ClaimStageParams struct {
	ID        string
	Attempt   int
	Status    string
	OldStatus string
}

func (q *Queries) ClaimStage(ctx context.Context, arg ClaimStageParams) (int, error) {
	row := q.db.QueryRow(ctx, claimStage,
		arg.ID,
		arg.Attempt,
		arg.Status,
		arg.OldStatus,
	)
	var attempt int
	err := row.Scan(&attempt)
	return attempt, err
}

const createApproval = `-- name: CreateApproval :exec
insert into approval(id,task_id,stage_id,kind,retry_no,status,title,content) values($1,$2,$3,$4,$5,'pending',$6,$7)
`

type CreateApprovalParams struct {
	ID      string
	TaskID  string
	StageID string
	Kind    string
	RetryNo int
	Title   string
	Content string
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) error {
	_, err := q.db.Exec(ctx, createApproval,
		arg.ID,
		arg.TaskID,
		arg.StageID,
		arg.Kind,
		arg.RetryNo,
		arg.Title,
		arg.Content,
	)
	return err
}

const createDeliverable = `-- name: CreateDeliverable :exec
insert into deliverable(id,task_id,stage_id,kind,uri,content,summary) values($1,$2,$3,'markdown',$4,$5,$6)
`

type CreateDeliverableParams struct {
	ID      string
	TaskID  string
	StageID string
	Uri     *string
	Content *string
	Summary *string
}

func (q *Queries) CreateDeliverable(ctx context.Context, arg CreateDeliverableParams) error {
	_, err := q.db.Exec(ctx, createDeliverable,
		arg.ID,
		arg.TaskID,
		arg.StageID,
		arg.Uri,
		arg.Content,
		arg.Summary,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
insert into task_event(event_id,task_id,seq,stage_key,agent,type,payload,ts) values($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateEventParams struct {
	EventID  string
	TaskID   string
	Seq      int64
	StageKey *string
	Agent    *string
	Type     string
	Payload  []byte
	Ts       pgtype.Timestamptz
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.EventID,
		arg.TaskID,
		arg.Seq,
		arg.StageKey,
		arg.Agent,
		arg.Type,
		arg.Payload,
		arg.Ts,
	)
	return err
}

const createProject = `-- name: CreateProject :exec
insert into project(id,name,github_owner,github_repo,default_branch,installation_id,local_path) values($1,$2,$3,$4,$5,$6,$7)
`

type CreateProjectParams struct {
	ID             string
	Name           string
	GithubOwner    string
	GithubRepo     string
	DefaultBranch  string
	InstallationID pgtype.Int8
	LocalPath      *string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.GithubOwner,
		arg.GithubRepo,
		arg.DefaultBranch,
		arg.InstallationID,
		arg.LocalPath,
	)
	return err
}

const createStage = `-- name: CreateStage :exec
insert into stage(id,task_id,stage_key,role,depends_on,status) values($1,$2,$3,$4,$5,'pending')
`

type CreateStageParams struct {
	ID        string
	TaskID    string
	StageKey  string
	Role      string
	DependsOn []string
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) error {
	_, err := q.db.Exec(ctx, createStage,
		arg.ID,
		arg.TaskID,
		arg.StageKey,
		arg.Role,
		arg.DependsOn,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
insert into task(id,project_id,command,status,created_by,pipeline,workspace) values($1,$2,$3,'queued',$4,$5,$6)
`

type CreateTaskParams struct {
	ID        string
	ProjectID string
	Command   string
	CreatedBy string
	Pipeline  []byte
	Workspace *string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.ProjectID,
		arg.Command,
		arg.CreatedBy,
		arg.Pipeline,
		arg.Workspace,
	)
	return err
}

const createUsage = `-- name: CreateUsage :exec
insert into usage_record(task_id,stage_key,agent,model,input_tokens,output_tokens,cache_read_tokens,cache_write_tokens,ts) values($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type CreateUsageParams struct {
	TaskID           string
	StageKey         *string
	Agent            *string
	Model            string
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	Ts               pgtype.Timestamptz
}

func (q *Queries) CreateUsage(ctx context.Context, arg CreateUsageParams) error {
	_, err := q.db.Exec(ctx, createUsage,
		arg.TaskID,
		arg.StageKey,
		arg.Agent,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.Ts,
	)
	return err
}

const decideApproval = `-- name: DecideApproval :execrows
update approval set status=$2,decision_feedback=$3,edited_content=$4,decided_by=$5,decided_via='web',decided_at=now(),version=version+1 where id=$1 and status='pending' and version=$6
`

type DecideApprovalParams struct {
	ID               string
	Status           string
	DecisionFeedback *string
	EditedContent    *string
	DecidedBy        *string
	Version          int
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideApproval,
		arg.ID,
		arg.Status,
		arg.DecisionFeedback,
		arg.EditedContent,
		arg.DecidedBy,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApproval = `-- name: GetApproval :one
select to_jsonb(a) from approval a where id=$1
`

func (q *Queries) GetApproval(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const getProject = `-- name: GetProject :one
select to_jsonb(p) from project p where id=$1
`

func (q *Queries) GetProject(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const getTask = `-- name: GetTask :one
select to_jsonb(t) from task t where id=$1
`

func (q *Queries) GetTask(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const latestDeliverableID = `-- name: LatestDeliverableID :one
select id from deliverable where stage_id=$1 order by created_at desc,id desc limit 1
`

func (q *Queries) LatestDeliverableID(ctx context.Context, stageID string) (string, error) {
	row := q.db.QueryRow(ctx, latestDeliverableID, stageID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listApprovals = `-- name: ListApprovals :many
select to_jsonb(a) from approval a where ($1::text is null or task_id::text=$1::text) and ($2::text is null or status=$2::text) and ($2::text is distinct from 'pending' or exists(select 1 from task t where t.id=a.task_id and t.status not in ('completed','failed','cancelled'))) order by requested_at,id
`

type ListApprovalsParams struct {
	TaskID *string
	Status *string
}

// A terminal Task's approvals can no longer be decided, so a pending filter skips them.
func (q *Queries) ListApprovals(ctx context.Context, arg ListApprovalsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listApprovals, arg.TaskID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
select (to_jsonb(e)-'id')::jsonb as event from task_event e where task_id=$1 and seq>$2 order by seq limit $3::integer
`

type ListEventsParams struct {
	TaskID  string
	Seq     int64
	Column3 int
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.TaskID, arg.Seq, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
select to_jsonb(p) from project p order by created_at,id
`

func (q *Queries) ListProjects(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStages = `-- name: ListStages :many
select to_jsonb(s) from stage s where task_id=$1 order by stage_key
`

func (q *Queries) ListStages(ctx context.Context, taskID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listStages, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
select to_jsonb(t) from task t where ($1::text is null or project_id::text=$1::text) and ($2::text[] is null or status=any($2::text[])) order by created_at desc,id
`

type ListTasksParams struct {
	ProjectID *string
	Statuses  []string
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.ProjectID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTask = `-- name: LockTask :one
select to_jsonb(t) from task t where id=$1 for update
`

func (q *Queries) LockTask(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockTask, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const nextSequence = `-- name: NextSequence :one
update task set event_seq=event_seq+1 where id=$1 returning event_seq
`

func (q *Queries) NextSequence(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, nextSequence, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const updateStage = `-- name: UpdateStage :execrows
update stage set status=$3,plan=$4,plan_retry_no=$5,deliverable_ref=$6,deliverable_summary=$7,deliverable_retry_no=$8,last_feedback=$9,blocked_reason=$10,retry_count=$5::integer+$8::integer,version=version+1,completed_at=case when $3='approved' then now() else completed_at end where id=$1 and attempt=$2 and status=$11 and version=$12
`

type UpdateStageParams struct {
	ID                 string
	Attempt            int
	Status             string
	Plan               *string
	PlanRetryNo        int
	DeliverableRef     *string
	DeliverableSummary *string
	DeliverableRetryNo int
	LastFeedback       *string
	BlockedReason      *string
	OldStatus          string
	OldVersion         int
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStage,
		arg.ID,
		arg.Attempt,
		arg.Status,
		arg.Plan,
		arg.PlanRetryNo,
		arg.DeliverableRef,
		arg.DeliverableSummary,
		arg.DeliverableRetryNo,
		arg.LastFeedback,
		arg.BlockedReason,
		arg.OldStatus,
		arg.OldVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execrows
update task set status=$2,version=version+1,updated_at=now() where id=$1 and version=$3
`

type UpdateTaskStatusParams struct {
	ID      string
	Status  string
	Version int
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
